- clean: ['~', '~/.config']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
#    ~/.gitignore_global: gitignore_global
    ~/.config/fish/config.fish:
      create: true
      path: config.fish
    ~/.tmux.conf: tmux.conf
#    ~/.vim: vim/
    ~/.vimrc: vimrc

- shell:
   - git submodule update --init --recursive
#   - ./pkginstall 
