- defaults:
    link:
        create: true
        relink: true

- clean: ['~']

- link:
    ~/.dotfiles: ''

    ~/.config/fish/completions: config/fish/completions/
    ~/.config/fish/functions: config/fish/functions/
    ~/.config/powerline: config/powerline/
    ~/.local/scripts: scripts/
    ~/.tmuxinator: tmuxinator/
    ~/.fonts: fonts/
    ~/.vim: vim/

    ~/.config/inkscape/icons/icons.svg: config/inkscape/icons/icons.svg
    ~/.config/fish/config.fish: config/fish/config.fish
    ~/.bash_profile: bash_profile
    ~/.bash_logout: bash_logout
    ~/.latexmkrc: latexmkrc
    ~/.gitconfig: gitconfig
    ~/.gitignore: gitignore
    ~/.tmux.conf: tmux.conf
    ~/.gnuplot: gnuplot
    ~/.inputrc: inputrc
    ~/.bashrc: bashrc
    ~/.toprc: toprc
    ~/.vimrc: vimrc

- shell:
   - [git submodule update --init --recursive, Updating submodules... ]
   -
     command: sudo ./pkginstall
     description: Running custom install script...
     stdin: true
     stdout: true
     stderr: true
