- clean: ['~', '~/.config']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig:
      create: true
      relink: true
      force: true
      path: gitconfig
    ~/.config/fish/config.fish:
      create: true
      relink: true
      force: true
      path: config/fish/config.fish
    ~/.fonts/truetype/Ubuntu Mono derivative Powerline.ttf:
      create: true
      relink: true
      force: true
      path: fonts/truetype/Ubuntu Mono derivative Powerline.ttf
    ~/.config/fish/functions:
      create: true
      relink: true
      force: true
      path: config/fish/functions/
    ~/.config/fish/completions:
      create: true
      relink: true
      force: true
      path: config/fish/completions/
    ~/.tmux.conf:
      create: true
      relink: true
      force: true
      path: tmux.conf
    ~/.tmuxinator:
      create: true
      relink: true
      force: true
      path: tmuxinator/
    ~/.vim:
      create: true
      relink: true
      force: true
      path: vim/
    ~/.vimrc:
      create: true
      relink: true
      force: true
      path: vimrc
    ~/.inputrc:
      create: true
      relink: true
      force: true
      path: inputrc
    ~/.toprc:
      create: true
      relink: true
      force: true
      path: toprc
    ~/.gitignore:
      create: true
      relink: true
      force: true
      path: gitignore
    ~/.bashrc:
      create: true
      relink: true
      force: true
      path: bashrc
    ~/.bash_profile:
      create: true
      relink: true
      force: true
      path: bash_profile
    ~/.bash_logout:
      create: true
      relink: true
      force: true
      path: bash_logout
    ~/.config/powerline/config.json:
      create: true
      relink: true
      force: true
      path: config/powerline/config.json
    ~/.local/bin:
      create: true
      relink: true
      force: true
      path: bin/

- shell:
   - git submodule update --init --recursive
   -
     command: sudo ./pkginstall
     description: Running custom install script...
     stdout: true
     stderr: true
