- clean: ['~', '~/.config']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
#    ~/.gitignore_global: gitignore_global
    ~/.config/fish/config.fish:
      create: true
      path: config/fish/config.fish
    ~/.config/fish/functions/df.fish:
       create: true
       path: config/fish/functions/df.fish
    ~/.fonts/truetype/Ubuntu Mono derivative Powerline.ttf:
       create: true
       path: fonts/truetype/Ubuntu Mono derivative Powerline.ttf
    ~/.config/fish/functions/du.fish: config/fish/functions/du.fish
    ~/.config/fish/functions/golive.fish: config/fish/functions/golive.fish
    ~/.config/fish/functions/ls.fish: config/fish/functions/ls.fish
    ~/.config/fish/functions/mutt.fish: config/fish/functions/mutt.fish
    ~/.config/fish/functions/ping.fish: config/fish/functions/ping.fish
    ~/.config/fish/functions/ps.fish: config/fish/functions/ps.fish
    ~/.config/fish/functions/tmux.fish: config/fish/functions/tmux.fish
    ~/.config/fish/functions/mux.fish: config/fish/functions/mux.fish
    ~/.config/fish/completions/tmuxinator.fish: config/fish/completions/tmuxinator.fish
    ~/.config/fish/completions/mux.fish: config/fish/completions/mux.fish
    ~/.tmux.conf: tmux.conf
    ~/.tmuxinator: tmuxinator/
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.inputrc: inputrc
    ~/.gitignore: gitignore
    ~/.bashrc: bashrc
    ~/.bash_profile: bash_profile
    ~/.bash_logout: bash_logout
    ~/.config/powerline/config.json: config/powerline/config.json
    ~/.local/bin: bin/

- shell:
   - git submodule update --init --recursive
#   - ./pkginstall 
