# ~/.tmuxinator/arclight.yml

name: LOCAL
root: ~/

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
pre: tmux start-server && cd ~

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247
#pre_window:

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: vim

# Controls whether the tmux session should be attached to automatically. Defaults to true.
#attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
#post: tmux -u new-session -A -t arclight

windows:
  - REMOTE: mosh nhill@fab.works tmux attach
  - MONITOR:
     layout: cd84,166x52,0,0[166x26,0,0{83x26,0,0,1,82x26,84,0,3},166x25,0,27{66x25,0,27,4,99x25,67,27,10}]
     panes:
           - dmesg -uwHtk
           - ipython --pylab
           - ping google.com
           - top -c
  - SHELL:
